global:
  scrape_interval: 15s

remote_write:
  - url: http://influxdb:8086/api/v2/write
    headers:
      Authorization: "Token supersecrettoken"
    write_relabel_configs:
      - source_labels: [__name__]
        regex: ".*"
        action: keep

scrape_configs:
  - job_name: node
    static_configs:
      - targets: ['host.docker.internal:9100']

  - job_name: process
    static_configs:
      - targets: ['process-exporter:9256']

  - job_name: gpu
    static_configs:
      - targets: ['nvidia-exporter:9400']
